{% set name = "flametree" %}
{% set version = "0.1.11" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flametree-{{ version }}.tar.gz
  sha256: c8eb81dea8c7f8261a2aa03d2bac98b1d21ebceec9c67efaac423f7c1b4fe061

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - flametree
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Edinburgh-Genome-Foundry/Flametree
  summary: Python file and zip operations made easy
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - tjacobs2
